import fs from "node:fs";
import path from "node:path";

export function resolveGenerationStrategy(paths, options = {}, env = process.env) {
  const provider = normalizeProvider(env.CODESPEC_LLM_PROVIDER || env.LLM_PROVIDER || readConfigProvider(paths));
  if (!provider || provider === "stub") {
    return {
      ok: true,
      generationMode: "stub",
      provider: null,
      model: options.model || null
    };
  }

  if (provider === "fake") {
    return {
      ok: true,
      generationMode: "direct",
      provider: "fake",
      model: options.model || env.CODESPEC_LLM_MODEL || env.LLM_MODEL || "fake-codespec-model"
    };
  }

  if (["openai", "anthropic"].includes(provider)) {
    const apiKey = env.CODESPEC_LLM_API_KEY || env.LLM_API_KEY;
    if (!apiKey) {
      return {
        ok: false,
        code: "LLM_NOT_CONFIGURED",
        provider,
        message: `缺少 ${provider} LLM 配置。请设置 CODESPEC_LLM_API_KEY 或改用 CODESPEC_LLM_PROVIDER=fake。`
      };
    }
  }

  return {
    ok: false,
    code: "LLM_PROVIDER_NOT_IMPLEMENTED",
    provider,
    message: `P2 暂未实现 LLM provider：${provider}。`
  };
}

export function fakeCompletion({ task, prompt, plan, design, model }) {
  if (task === "design") {
    const modules = plan.modules
      .map((module) => `- ${module.name}: ${module.path} - ${module.description}`)
      .join("\n");
    return {
      text: `# CodeSpec Design

<!-- generated by codespec fake direct -->

Provider: fake
Model: ${model}

## 1. 组件定位

Fake direct design generated from scan and plan.

## 2. 架构总览

Project: ${plan.projectName}
Language: ${plan.language || "unknown"}
Primary extension: ${plan.primaryExtension || "unknown"}

## 3. 模块设计

${modules}

## 4. 核心流程

The direct generator first scans the repository, then plans modules, then produces this design artifact.

## 5. 接口设计

待真实 LLM provider 接入后补充。

## 6. 数据模型

待真实 LLM provider 接入后补充。

## 7. 配置与部署

Fake provider does not call a network API.

## 8. DFX 设计

Generation artifacts remain isolated under .codespec-cli/runs before apply.

## 9. 风险与约束

This is deterministic fake direct output for tests.
`,
      usage: { input: estimateTokens(prompt), output: 0 }
    };
  }

  return {
    text: `# CodeSpec SPEC

<!-- generated by codespec fake direct -->

Derived from design.
Provider: fake
Model: ${model}

## 1. 组件定位

This fake spec is derived from the generated design document, not directly from repository source files.

## 2. 领域术语

- Design-derived specification: a SPEC artifact generated after design.md exists.

## 3. 角色与边界

CodeSpec CLI owns artifact writing and apply protection.

## 4. DFX 约束

Generated documents are staged in a run directory before apply.

## 5. 功能规格

- Produce spec.md only after design.md generation.
- Preserve apply overwrite protection.

## 6. 验收标准

- The spec prompt includes the generated design content.
- The resulting spec contains the marker "Derived from design".

Design summary:
${design.split(/\r?\n/).slice(0, 8).join("\n")}
`,
    usage: { input: estimateTokens(prompt), output: 0 }
  };
}

function normalizeProvider(provider) {
  return String(provider || "").trim().toLowerCase();
}

function readConfigProvider(paths) {
  const file = path.join(paths.runtime, "config.yaml");
  if (!fs.existsSync(file)) return "";
  const text = fs.readFileSync(file, "utf8");
  const lines = text.split(/\r?\n/);
  const start = lines.findIndex((line) => line === "generation:");
  if (start === -1) return "";
  const generation = [];
  for (const line of lines.slice(start + 1)) {
    if (line && !line.startsWith(" ")) break;
    generation.push(line);
  }
  return generation.join("\n").match(/^  provider:\s*["']?([^"'\s]+)["']?\s*$/m)?.[1] || "";
}

function estimateTokens(text) {
  return Math.ceil(String(text || "").length / 4);
}
