import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { projectPaths } from "./project.js";
import { ensureDir, rel, slugify, writeJson, readJson } from "./util.js";
import { scanRepository, normalizePath } from "./scanner.js";
import { planModules } from "./planner.js";
import { fakeCompletion, resolveGenerationStrategy } from "./llm.js";
import { runDirectGeneration } from "./generator/direct.js";
import { runReactGeneration } from "./generator/react.js";
import { createWorkspaceGuard, runExternalGeneration, runRunnerTask } from "./generator/external.js";
import { commonOutputRules, requiredDesignSections, requiredSpecSections } from "./generator/templates.js";

const STUB_MARKER = "<!-- generated by metaspec stub -->";

export function generateDocs(options = {}) {
  const paths = projectPaths(options);
  progress(options, "检查 metaspec 项目结构");
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const preflightStrategy = resolveGenerationStrategy(paths, options);
  if (!preflightStrategy.ok) return preflightStrategy;

  const run = createRun(paths, "generate", options);
  progress(options, `创建 run ${run.manifest.runId}`);
  const logsDir = path.join(run.dir, "logs");
  ensureDir(logsDir);

  progress(options, "扫描仓库文件");
  const scan = scanRepository(paths.root);
  progress(options, `扫描完成：纳入 ${scan.includedFiles.length} 个文件，忽略 ${scan.ignoredFiles.count} 个条目`);
  progress(options, "规划模块");
  const plan = planModules(paths.root, scan);
  progress(options, `模块规划完成：${plan.modules.length} 个模块，主语言 ${plan.language || "unknown"}`);
  writeJson(path.join(logsDir, "scan.json"), scan);
  writeJson(path.join(run.dir, "plan.json"), plan);

  const strategy = resolveGenerationStrategy(paths, options, process.env, { scan, plan });
  if (!strategy.ok) return failRun(run, strategy);
  progress(options, `生成策略：runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`);

  const specPath = path.join(run.dir, "spec.md");
  const designPath = path.join(run.dir, "design.md");
  if (strategy.generationMode === "direct") {
    progress(options, "整体 direct：生成 design.md，然后从 design.md 反推 spec.md");
    const direct =
      strategy.provider === "fake"
        ? runDirectGeneration({ paths, run, scan, plan, strategy })
        : runExternalGeneration({ paths, run, scan, plan, strategy });
    if (!direct.ok && !direct.design) return failRun(run, direct);
    fs.writeFileSync(designPath, direct.design, "utf8");
    fs.writeFileSync(specPath, direct.spec, "utf8");
    applyGenerationMetadata(run.manifest, {
      generationMode: "direct",
      runner: strategy.runner,
      provider: direct.provider,
      model: direct.model,
      tokens: direct.tokens,
      logs: direct.logs,
      warnings:
        strategy.provider === "fake"
          ? ["P2 fake direct output; no real network LLM was called."]
          : ["P2 CLI runner direct output; artifacts were staged under the run directory."],
      reason: strategy.generationReason
    });
  } else if (strategy.generationMode === "react") {
    progress(options, `模块优先生成：逐模块生成文档，合成 design.md，然后反推 spec.md（${plan.modules.length} 个模块，预计 ${plan.modules.length + 2} 次 runner 调用）`);
    const react = runReactGeneration({ paths, run, scan, plan, strategy, progress: options.progress });
    if (!react.ok) return failRun(run, react);
    fs.writeFileSync(designPath, react.design, "utf8");
    fs.writeFileSync(specPath, react.spec, "utf8");
    applyGenerationMetadata(run.manifest, {
      generationMode: "react",
      runner: strategy.runner,
      provider: react.provider,
      model: react.model,
      tokens: react.tokens,
      logs: react.logs,
      modules: react.modules,
      warnings:
        strategy.provider === "fake"
          ? ["P3 fake react output; no real network LLM was called."]
          : ["P3 CLI runner react output; module artifacts were staged under the run directory."],
      reason: react.reason
    });
  } else {
    progress(options, "未发现可用本地 runner，写入 deterministic stub");
    fs.writeFileSync(designPath, designStub(paths.root, run.manifest), "utf8");
    fs.writeFileSync(specPath, specStub(paths.root, run.manifest), "utf8");
    run.manifest.generationReason = strategy.generationReason;
    run.manifest.warnings = ["未发现可用的本地生成工具，已使用 deterministic stub。"];
  }

  run.manifest.artifacts.spec = "spec.md";
  run.manifest.artifacts.design = "design.md";
  run.manifest.artifacts.plan = "plan.json";
  run.manifest.logs.scan = "logs/scan.json";
  run.manifest.scanSummary = {
    totalFiles: scan.totalFiles,
    includedFiles: scan.includedFiles.length,
    ignoredFiles: scan.ignoredFiles.count,
    readmeFiles: scan.readmeFiles.map((file) => file.path),
    docsFiles: scan.docsFiles.map((file) => file.path)
  };
  run.manifest.planSummary = {
    modules: plan.modules.length,
    language: plan.language,
    primaryExtension: plan.primaryExtension
  };
  writeManifest(paths, run);
  progress(options, "写入 manifest 和 latest 指针");

  return {
    ok: true,
    runId: run.manifest.runId,
    status: run.manifest.status,
    artifacts: [rel(paths.root, specPath), rel(paths.root, designPath)],
    message: `已生成候选文档：${run.manifest.runId}`,
    summary: {
      runner: run.manifest.runner || "auto",
      mode: displayGenerationMode(run.manifest.generationMode),
      model: run.manifest.model || "none",
      files: `${scan.includedFiles.length} included / ${scan.ignoredFiles.count} ignored`,
      modules: plan.modules.length,
      run: rel(paths.root, run.dir)
    },
    sections: [
      {
        title: "产物",
        items: [rel(paths.root, specPath), rel(paths.root, designPath), rel(paths.root, path.join(run.dir, "plan.json")), rel(paths.root, path.join(logsDir, "scan.json"))]
      },
      {
        title: "审查建议",
        items: ["先执行 metaspec show 查看摘要", "确认内容后执行 metaspec apply 写入 metaspec/specs"]
      }
    ],
    next: ["metaspec show", "metaspec apply"]
  };
}

export function generateModule(modulePath, options = {}) {
  if (!modulePath) {
    return {
      ok: false,
      code: "MISSING_MODULE_PATH",
      message: "缺少模块路径：metaspec generate module <path>"
    };
  }
  const paths = projectPaths(options);
  progress(options, "检查 metaspec 项目结构");
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;

  const relativeModulePath = normalizeModulePath(paths.root, modulePath);
  progress(options, `准备模块路径：${relativeModulePath}`);
  const scan = scanRepository(paths.root);
  const plan = moduleOnlyPlan(paths.root, relativeModulePath, scan);
  const strategy = resolveGenerationStrategy(paths, options, process.env, { scan, plan });
  if (!strategy.ok) return strategy;
  progress(options, `生成策略：runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`);

  const latest = loadLatestRun(paths);
  const run = latest ? { dir: latest.dir, manifest: latest.manifest } : createRun(paths, "generate", options);
  const modulesDir = path.join(run.dir, "modules");
  ensureDir(modulesDir);
  const logsDir = path.join(run.dir, "logs");
  ensureDir(logsDir);

  if (!modulePathExists(paths.root, relativeModulePath)) {
    const warning = `module path not found: ${relativeModulePath}`;
    if (!run.manifest.warnings.includes(warning)) run.manifest.warnings.push(warning);
  }
  const fileName = `${slugify(relativeModulePath) || "project-root"}.md`;
  const moduleFile = path.join(modulesDir, fileName);
  const moduleResult =
    strategy.generationMode === "stub"
      ? {
          ok: true,
          content: moduleStub(relativeModulePath, run.manifest),
          logs: {},
          tokens: run.manifest.tokens,
          warnings: ["未发现可用的本地生成工具，已使用 deterministic stub。"]
        }
      : runModuleGeneration({ paths, run, scan, module: plan.modules[0], strategy, fileName });
  if (!moduleResult.ok) return failRun(run, moduleResult);
  fs.writeFileSync(moduleFile, moduleResult.content, "utf8");

  const artifact = `modules/${fileName}`;
  if (!run.manifest.artifacts.modules.includes(artifact)) run.manifest.artifacts.modules.push(artifact);
  if (!run.manifest.logs.scan) {
    writeJson(path.join(logsDir, "scan.json"), scan);
    writeJson(path.join(run.dir, "plan.json"), plan);
    run.manifest.logs.scan = "logs/scan.json";
    run.manifest.artifacts.plan = "plan.json";
    run.manifest.scanSummary = {
      totalFiles: scan.totalFiles,
      includedFiles: scan.includedFiles.length,
      ignoredFiles: scan.ignoredFiles.count,
      readmeFiles: scan.readmeFiles.map((file) => file.path),
      docsFiles: scan.docsFiles.map((file) => file.path)
    };
    run.manifest.planSummary = {
      modules: plan.modules.length,
      language: plan.language,
      primaryExtension: plan.primaryExtension
    };
  }
  applyModuleGenerationMetadata(run.manifest, strategy, moduleResult);
  run.manifest.updatedAt = new Date().toISOString();
  writeManifest(paths, run);

  return {
    ok: true,
    runId: run.manifest.runId,
    module: relativeModulePath,
    artifact: rel(paths.root, moduleFile),
    message: `已生成模块候选文档：${relativeModulePath}`,
    summary: {
      runner: run.manifest.runner || "auto",
      mode: displayGenerationMode(run.manifest.generationMode),
      model: run.manifest.model || "none",
      run: rel(paths.root, run.dir)
    },
    sections: [{ title: "产物", items: [rel(paths.root, moduleFile)] }],
    next: ["metaspec show"]
  };
}

function runModuleGeneration({ paths, run, scan, module, strategy, fileName }) {
  const promptsDir = path.join(run.dir, "logs/prompts/modules");
  ensureDir(promptsDir);
  const promptFile = path.join(promptsDir, fileName);
  const prompt = buildModulePrompt(scan, module, strategy);
  fs.writeFileSync(promptFile, prompt, "utf8");

  if (strategy.provider === "fake") {
    const result = fakeCompletion({ task: "module", prompt, plan: module, model: strategy.model });
    const tokens = { input: result.usage.input, output: result.usage.output };
    const isReact = strategy.generationMode === "react";
    const logFile = path.join(run.dir, isReact ? "logs/react.json" : "logs/module.json");
    writeJson(logFile, {
      runner: strategy.runner,
      provider: strategy.provider,
      model: strategy.model,
      reason: strategy.generationReason,
      modules: [{ name: module.name, path: module.path, artifact: `modules/${fileName}`, prompt: rel(run.dir, promptFile), usage: result.usage }],
      tokens
    });
    return {
      ok: true,
      content: result.text,
      tokens,
      logs: {
        ...(isReact ? { react: rel(run.dir, logFile) } : { module: rel(run.dir, logFile) }),
        prompts: { modules: { [module.path]: rel(run.dir, promptFile) } }
      },
      warnings: [isReact ? "P3 fake react module output; no real network LLM was called." : "P2 fake direct module output; no real network LLM was called."]
    };
  }

  const guard = createWorkspaceGuard(paths, run);
  const result = runRunnerTask({ paths, run, strategy, task: `module-${slugify(module.path) || "project-root"}`, prompt });
  if (!result.ok) return result;
  const workspaceError = guard.changed();
  if (workspaceError) return workspaceError;
  const tokens = { input: Math.ceil(prompt.length / 4), output: Math.ceil(result.content.length / 4) };
  const externalLogFile = path.join(run.dir, "logs/external.json");
  writeJson(externalLogFile, {
    runner: strategy.runner,
    model: result.model || strategy.model,
    calls: [result.log],
    prompts: { modules: { [module.path]: rel(run.dir, promptFile) } },
    tokens
  });
  const isReact = strategy.generationMode === "react";
  const moduleLogFile = path.join(run.dir, "logs/module.json");
  writeJson(moduleLogFile, {
    runner: strategy.runner,
    provider: strategy.provider,
    model: result.model || strategy.model,
    reason: strategy.generationReason,
    modules: [{ name: module.name, path: module.path, artifact: `modules/${fileName}`, prompt: rel(run.dir, promptFile), runnerLog: result.log }],
    tokens
  });
  const reactLogFile = path.join(run.dir, "logs/react.json");
  if (strategy.generationMode === "react") {
    writeJson(reactLogFile, {
      runner: strategy.runner,
      provider: strategy.provider,
      model: result.model || strategy.model,
      reason: strategy.generationReason,
      modules: [{ name: module.name, path: module.path, artifact: `modules/${fileName}`, prompt: rel(run.dir, promptFile), runnerLog: result.log }],
      tokens
    });
  }
  return {
    ok: true,
    content: result.content,
    tokens,
    model: result.model || strategy.model,
    logs: {
      external: rel(run.dir, externalLogFile),
      ...(isReact ? { react: rel(run.dir, reactLogFile) } : { module: rel(run.dir, moduleLogFile) }),
      prompts: { modules: { [module.path]: rel(run.dir, promptFile) } }
    },
    warnings: ["CLI runner module output; artifact was staged under the run directory."]
  };
}

function buildModulePrompt(scan, module, strategy) {
  const moduleFiles = scan.includedFiles.filter((file) => module.path === "." || file === module.path || file.startsWith(`${module.path}/`));
  return `你是 MetaSpec 模块文档生成 runner（${strategy.runner}）。
当前任务只允许读取和分析仓库。
禁止修改任何文件。
禁止写入 metaspec/specs。
请只输出模块 Markdown。模块文档是白盒中间材料，可以包含文件、类、框架、数据结构等实现细节。

${commonOutputRules()}

模块文档要求：
1. 说明模块定位、目录结构、核心组件、核心流程、接口与数据结构、关键约束。
2. 必须基于给定模块路径和仓库只读分析，不要编造不存在的文件。
3. 该文档只写入 run/modules，不会直接成为最终 SPEC。

模块：${module.name}
路径：${module.path}
描述：${module.description}

模块文件：
${moduleFiles.slice(0, 80).map((file) => `- ${file}`).join("\n") || "- none"}

README context:
${scan.readmeFiles.map((file) => `--- ${file.path}${file.truncated ? " (truncated)" : ""} ---\n${file.content}`).join("\n\n") || "(none)"}

Docs context:
${scan.docsFiles.map((file) => `--- ${file.path}${file.truncated ? " (truncated)" : ""} ---\n${file.content}`).join("\n\n") || "(none)"}
`;
}

export function showLatestRun(options = {}) {
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const latest = loadLatestRun(paths);
  if (!latest) {
    return {
      ok: false,
      code: "NO_GENERATED_RUN",
      message: "未发现候选文档。请先执行 metaspec generate。"
    };
  }
  if (options.json) return latest.manifest;

  const manifest = latest.manifest;
  const modules = manifest.artifacts.modules || [];
  const plan = readRunJson(latest, manifest.artifacts.plan);
  const scan = readRunJson(latest, manifest.logs?.scan);
  const plannedModules = plan?.modules?.length ?? manifest.planSummary?.modules ?? 0;
  const includedFiles = scan?.includedFiles?.length ?? manifest.scanSummary?.includedFiles ?? null;
  const hasFullArtifacts = Boolean(manifest.artifacts.spec && manifest.artifacts.design);
  return {
    ok: true,
    runId: manifest.runId,
    message: `候选文档：${manifest.runId}`,
    items: [
      `状态：${manifest.status}`,
      `Commit：${manifest.commitId || "unknown"}`,
      "",
      "产物：",
      manifest.artifacts.spec ? `  ${manifest.artifacts.spec}` : "  spec.md 未生成",
      manifest.artifacts.design ? `  ${manifest.artifacts.design}` : "  design.md 未生成",
      `  modules/ ${modules.length} files`,
      manifest.artifacts.plan ? `  ${manifest.artifacts.plan}` : "  plan.json 未生成",
      manifest.logs?.scan ? `  ${manifest.logs.scan}` : "  logs/scan.json 未生成",
      "",
      "摘要：",
      `  generation mode: ${displayGenerationMode(manifest.generationMode)}`,
      `  runner: ${manifest.runner || "auto"}`,
      `  provider: ${manifest.provider || "none"}`,
      `  model: ${manifest.model || "none"}`,
      `  included files: ${includedFiles ?? "unknown"}`,
      `  planned modules: ${plannedModules}`,
      "",
      "文件位置：",
      `  ${rel(paths.root, latest.dir)}/`,
      ...(hasFullArtifacts ? [] : ["", "提示：这是 module-only run，请先执行 metaspec generate 后再 apply。"])
    ],
    next: hasFullArtifacts ? ["metaspec apply"] : ["metaspec generate"]
  };
}

export function applyLatestRun(options = {}) {
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const latest = loadLatestRun(paths);
  if (!latest) {
    return {
      ok: false,
      code: "NO_GENERATED_RUN",
      message: "未发现候选文档。请先执行 metaspec generate。"
    };
  }
  if (latest.manifest.status === "partial_success" && !options.force) {
    return {
      ok: false,
      code: "APPLY_PARTIAL_SUCCESS_REQUIRES_FORCE",
      message: "最近一次候选文档为 partial_success。如确认仍要应用，请执行 metaspec apply --force。"
    };
  }

  const specSource = path.join(latest.dir, "spec.md");
  const designSource = path.join(latest.dir, "design.md");
  const missing = [specSource, designSource].filter((file) => !fs.existsSync(file));
  if (missing.length) {
    return {
      ok: false,
      code: "RUN_ARTIFACT_MISSING",
      message: `候选文档不完整：${missing.map((file) => rel(paths.root, file)).join(", ")}`
    };
  }

  const quality = validateApplyArtifacts(specSource, designSource);
  if (!quality.ok) return quality;

  const specTarget = path.join(paths.specs, "spec.md");
  const designTarget = path.join(paths.specs, "design.md");
  const existing = [specTarget, designTarget].filter((file) => fs.existsSync(file));
  if (existing.length && !options.force) {
    return {
      ok: false,
      code: "APPLY_OVERWRITE_REQUIRED",
      message: "已存在 metaspec/specs/spec.md 或 metaspec/specs/design.md。如需覆盖，请执行 metaspec apply --force。",
      existing: existing.map((file) => rel(paths.root, file))
    };
  }

  fs.mkdirSync(paths.specs, { recursive: true });
  fs.copyFileSync(specSource, specTarget);
  fs.copyFileSync(designSource, designTarget);

  latest.manifest.applied = true;
  latest.manifest.appliedAt = new Date().toISOString();
  writeManifest(paths, latest);

  return {
    ok: true,
    runId: latest.manifest.runId,
    applied: [rel(paths.root, specTarget), rel(paths.root, designTarget)],
    message: `已应用候选文档：${latest.manifest.runId}`,
    items: [rel(paths.root, specTarget), rel(paths.root, designTarget)]
  };
}

function validateApplyArtifacts(specFile, designFile) {
  const spec = fs.readFileSync(specFile, "utf8");
  const design = fs.readFileSync(designFile, "utf8");
  const findings = [];
  if (!spec.trim()) findings.push({ level: "error", code: "SPEC_EMPTY", path: "spec.md", message: "spec.md 为空。" });
  if (!design.trim()) findings.push({ level: "error", code: "DESIGN_EMPTY", path: "design.md", message: "design.md 为空。" });

  for (const section of requiredSpecSections()) {
    if (!containsSection(spec, section)) {
      findings.push({ level: "error", code: "SPEC_SECTION_MISSING", path: "spec.md", message: `spec.md 缺少固定章节：${section}` });
    }
  }
  for (const section of requiredDesignSections()) {
    if (!containsSection(design, section)) {
      findings.push({ level: "error", code: "DESIGN_SECTION_MISSING", path: "design.md", message: `design.md 缺少固定章节：${section}` });
    }
  }
  for (const finding of forbiddenGeneratedOutput(spec, "spec.md")) findings.push(finding);
  for (const finding of forbiddenGeneratedOutput(design, "design.md")) findings.push(finding);

  if (!findings.length) return { ok: true };
  return {
    ok: false,
    code: "APPLY_QUALITY_FAILED",
    message: "候选文档未通过 apply 前质量检查。",
    findings,
    next: ["metaspec show", "查看 .metaspec-cli/runs/{run-id}/spec.md 和 design.md"]
  };
}

function containsSection(text, section) {
  return text.replace(/\s+/g, "").includes(section.replace(/\s+/g, ""));
}

function forbiddenGeneratedOutput(text, file) {
  const findings = [];
  const trimmed = text.trim();
  if (/^```(?:md|markdown)?\s*#/i.test(trimmed) && /```\s*$/i.test(trimmed)) {
    findings.push({ level: "error", code: "WHOLE_DOCUMENT_CODE_FENCE", path: file, message: `${file} 被整体包裹在 Markdown 代码围栏中。` });
  }
  const forbidden = [
    { pattern: /\b(?:this|the)\s+sandbox\b|\bsandbox\s+environment\b|\bread-?only\s+sandbox\b/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "sandbox environment" },
    { pattern: /\bread-?only\s+filesystem\b|\bfilesystem\s+access\b/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "filesystem access" },
    { pattern: /\bread-?only\s+(?:mode|environment|access)\b/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "read-only environment" },
    { pattern: /cannot write files|could not write files|can't write files/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "cannot write files" },
    { pattern: /copy (?:this|the following|into|to your repo)/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "copy into repo" }
  ];
  for (const item of forbidden) {
    if (item.pattern.test(text)) {
      findings.push({ level: "error", code: item.code, path: file, message: `${file} 包含 runner 环境说明：${item.label}` });
    }
  }
  return findings;
}

function progress(options, message) {
  if (typeof options.progress === "function") options.progress(message);
}

function displayGenerationMode(mode) {
  if (mode === "react") return "module-first";
  if (mode === "direct") return "whole-project-direct";
  return mode || "unknown";
}

function createRun(paths, type, options = {}) {
  const runId = uniqueRunId(paths);
  const dir = path.join(paths.runtime, "runs", runId);
  fs.mkdirSync(dir, { recursive: true });
  const manifest = {
    runId,
    type,
    status: "generated",
    createdAt: new Date().toISOString(),
    root: paths.root,
    commitId: currentCommit(paths.root),
    runner: options.runner || "auto",
    generationMode: "stub",
    provider: null,
    model: options.model || null,
    probeModels: {
      requested: Boolean(options.probe_models),
      status: options.probe_models ? "not_implemented" : "not_requested"
    },
    artifacts: {
      spec: null,
      design: null,
      plan: null,
      modules: []
    },
    logs: {
      scan: null,
      llm: null,
      prompts: {}
    },
    warnings: ["P0 deterministic stub output; no LLM was called."],
    tokens: {
      input: 0,
      output: 0
    },
    applied: false
  };
  return { dir, manifest };
}

function applyGenerationMetadata(manifest, metadata) {
  manifest.runner = metadata.runner || manifest.runner;
  manifest.generationMode = metadata.generationMode;
  manifest.provider = metadata.provider || null;
  manifest.model = metadata.model || null;
  manifest.tokens = metadata.tokens || manifest.tokens;
  manifest.generationReason = metadata.reason || null;
  manifest.warnings = metadata.warnings || manifest.warnings;
  if (metadata.logs?.llm) manifest.logs.llm = metadata.logs.llm;
  if (metadata.logs?.react) manifest.logs.react = metadata.logs.react;
  if (metadata.logs?.external) manifest.logs.external = metadata.logs.external;
  if (metadata.logs?.prompts) manifest.logs.prompts = metadata.logs.prompts;
  if (metadata.modules) manifest.artifacts.modules = metadata.modules;
}

function applyModuleGenerationMetadata(manifest, strategy, result) {
  manifest.runner = strategy.runner || manifest.runner;
  manifest.generationMode = strategy.generationMode;
  manifest.provider = strategy.provider || null;
  manifest.model = result.model || strategy.model || null;
  manifest.tokens = result.tokens || manifest.tokens;
  manifest.generationReason = strategy.generationReason || null;
  if (result.warnings) {
    manifest.warnings = [...new Set([...manifest.warnings, ...result.warnings])];
  }
  if (result.logs?.external) manifest.logs.external = result.logs.external;
  if (result.logs?.react) manifest.logs.react = result.logs.react;
  if (result.logs?.module) manifest.logs.module = result.logs.module;
  if (result.logs?.prompts) {
    manifest.logs.prompts = {
      ...(manifest.logs.prompts || {}),
      ...(result.logs.prompts || {})
    };
  }
}

function failRun(run, error) {
  run.manifest.status = "failed";
  run.manifest.error = {
    code: error.code,
    message: error.message
  };
  writeJson(path.join(run.dir, "manifest.json"), run.manifest);
  return error;
}

function writeManifest(paths, run) {
  writeJson(path.join(run.dir, "manifest.json"), run.manifest);
  writeJson(path.join(paths.runtime, "runs", "latest.json"), {
    runId: run.manifest.runId,
    manifest: rel(paths.root, path.join(run.dir, "manifest.json"))
  });
}

function loadLatestRun(paths) {
  const latestFile = path.join(paths.runtime, "runs", "latest.json");
  const latest = readJson(latestFile);
  if (latest?.runId) {
    const dir = path.join(paths.runtime, "runs", latest.runId);
    const manifest = readJson(path.join(dir, "manifest.json"));
    if (manifest) return { dir, manifest };
  }

  const runsDir = path.join(paths.runtime, "runs");
  if (!fs.existsSync(runsDir)) return null;
  const manifests = fs
    .readdirSync(runsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const dir = path.join(runsDir, entry.name);
      return { dir, manifest: readJson(path.join(dir, "manifest.json")) };
    })
    .filter((run) => run.manifest?.createdAt && run.manifest.status !== "failed")
    .sort((a, b) => String(b.manifest.createdAt).localeCompare(String(a.manifest.createdAt)));
  return manifests[0] || null;
}

function projectInitializationError(paths) {
  if (!fs.existsSync(paths.runtime) || !fs.existsSync(paths.metaspec)) {
    return {
      ok: false,
      code: "METASPEC_NOT_INITIALIZED",
      message: "缺少 metaspec 项目结构。请先执行 metaspec init。",
      next: ["metaspec init"]
    };
  }
  return null;
}

function validateModuleRunner(options) {
  const runner = options.runner || "auto";
  if (runner === "auto") return null;
  return {
    ok: false,
    code: "RUNNER_NOT_IMPLEMENTED",
    runner,
    message: `P0 暂未实现 --runner ${runner}。请使用默认 runner 或 --runner auto。`,
    next: ["metaspec generate"]
  };
}

function uniqueRunId(paths) {
  const base = timestampId();
  let runId = base;
  let suffix = 1;
  while (fs.existsSync(path.join(paths.runtime, "runs", runId))) {
    suffix += 1;
    runId = `${base}-${suffix}`;
  }
  return runId;
}

function timestampId(date = new Date()) {
  const pad = (value, size = 2) => String(value).padStart(size, "0");
  return [
    date.getFullYear(),
    pad(date.getMonth() + 1),
    pad(date.getDate()),
    pad(date.getHours()),
    pad(date.getMinutes()),
    pad(date.getSeconds()),
    pad(date.getMilliseconds(), 3)
  ].join("");
}

function currentCommit(root) {
  const result = spawnSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
    timeout: 2000
  });
  return result.status === 0 ? result.stdout.trim() : null;
}

function normalizeModulePath(root, modulePath) {
  const resolved = path.isAbsolute(modulePath) ? modulePath : path.join(root, modulePath);
  const relative = normalizePath(path.relative(root, resolved));
  return relative && !relative.startsWith("..") ? relative : normalizePath(modulePath);
}

function modulePathExists(root, modulePath) {
  if (modulePath === ".") return true;
  return fs.existsSync(path.join(root, modulePath));
}

function readRunJson(run, relativePath) {
  if (!relativePath) return null;
  return readJson(path.join(run.dir, relativePath), null);
}

function moduleOnlyPlan(root, modulePath, scan) {
  const primaryExtension = scan.primaryExtension || null;
  return {
    projectName: path.basename(root),
    language: null,
    primaryExtension,
    modules: [
      {
        name: moduleName(modulePath),
        path: modulePath,
        description: modulePath === "." ? "Project root module requested by user." : `Module requested by user at ${modulePath}.`
      }
    ]
  };
}

function moduleName(modulePath) {
  if (modulePath === ".") return "Project Root";
  const base = modulePath.split("/").filter(Boolean).pop() || "Module";
  return base
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function designStub(root, manifest) {
  return `${STUB_MARKER}
# MetaSpec 实现设计文档

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. 设计概述

这是 P0 deterministic stub 设计文档，用于验证 MetaSpec CLI 的候选文档生成链路。

## 2. 系统架构

P0 不连接真实 LLM，也不调用外部 agent。CLI 只负责创建 run 目录、写入产物和维护 manifest。

## 3. 数据模型

manifest.json 记录 runId、状态、产物、runner、模型探测设计和 apply 状态。

## 4. 接口设计

用户入口为 metaspec generate、metaspec show、metaspec apply 和 metaspec generate module <path>。

## 5. 核心流程设计

generate 写入候选文档，show 展示最近 run，apply 在覆盖保护下写入 metaspec/specs。

## 6. 算法设计

stub 模式不包含复杂算法。

## 7. 缓存设计

stub 模式不使用缓存。

## 8. 异常处理设计

默认不覆盖已有权威文档，必须显式传入 --force。

## 9. 监控与日志

run 目录保留 manifest 和生成日志。

## 10. 安全设计

stub 内容仅用于 P0 验收，不能代表真实项目设计结论。
`;
}

function specStub(root, manifest) {
  return `${STUB_MARKER}
# MetaSpec SPEC

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. 组件定位

该组件通过 MetaSpec CLI 管理候选文档与权威文档的发布流程。

## 2. 领域术语

- 候选文档：生成后保存在 run 目录、尚未应用的文档。
- 权威文档：位于 metaspec/specs 的 spec.md 与 design.md。
- run：一次生成动作产生的隔离结果目录。

## 3. 角色与边界

CLI 负责落盘、展示和应用文档。P0 不让任何外部 agent 写入权威文档。

## 4. DFX约束

应用候选文档时必须遵守覆盖保护；已有权威文档默认不被覆盖。

## 5. 核心能力

- 用户可以生成候选 spec.md 与 design.md。
- 用户可以查看最近一次候选文档摘要。
- 用户可以显式应用最近一次候选文档。
- 用户可以为单个模块生成 stub 审查材料。

## 6. 数据约束

- generate 只写入 .metaspec-cli/runs。
- show 可以返回最近 run 的 manifest。
- apply 在无 --force 且目标存在时失败。
`;
}

function moduleStub(modulePath, manifest) {
  return `${STUB_MARKER}
# Module Design: ${modulePath}

Run: ${manifest.runId}

## 1. 模块定位

这是针对 ${modulePath} 的 P0 deterministic stub 模块文档。

## 2. 目录结构

P0 不扫描真实文件树；后续阶段会补充仓库扫描和模块规划。

## 3. 核心组件

待真实生成阶段根据代码分析补充。

## 4. 核心流程

该文件只保存在 run 的 modules/ 目录中，不会由 apply 写入 metaspec/specs。

## 5. 接口与数据结构

待确认。

## 6. 关键约束

P0 不调用 LLM 或外部 runner。
`;
}
