import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { projectPaths } from "./project.js";
import { ensureDir, rel, slugify, writeJson, readJson } from "./util.js";
import { scanRepository, normalizePath } from "./scanner.js";
import { planModules } from "./planner.js";
import { resolveGenerationStrategy } from "./llm.js";
import { runDirectGeneration } from "./generator/direct.js";

const STUB_MARKER = "<!-- generated by codespec stub -->";

export function generateDocs(options = {}) {
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const runnerError = validateRunner(options);
  if (runnerError) return runnerError;
  const strategy = resolveGenerationStrategy(paths, options);
  if (!strategy.ok) return strategy;

  const run = createRun(paths, "generate", options);
  const logsDir = path.join(run.dir, "logs");
  ensureDir(logsDir);

  const scan = scanRepository(paths.root);
  const plan = planModules(paths.root, scan);
  writeJson(path.join(logsDir, "scan.json"), scan);
  writeJson(path.join(run.dir, "plan.json"), plan);

  const specPath = path.join(run.dir, "spec.md");
  const designPath = path.join(run.dir, "design.md");
  if (strategy.generationMode === "direct") {
    const direct = runDirectGeneration({ paths, run, scan, plan, strategy });
    fs.writeFileSync(designPath, direct.design, "utf8");
    fs.writeFileSync(specPath, direct.spec, "utf8");
    run.manifest.generationMode = "direct";
    run.manifest.provider = direct.provider;
    run.manifest.model = direct.model;
    run.manifest.tokens = direct.tokens;
    run.manifest.logs.llm = direct.logs.llm;
    run.manifest.logs.prompts = direct.logs.prompts;
    run.manifest.warnings = ["P2 fake direct output; no real network LLM was called."];
  } else {
    fs.writeFileSync(designPath, designStub(paths.root, run.manifest), "utf8");
    fs.writeFileSync(specPath, specStub(paths.root, run.manifest), "utf8");
  }

  run.manifest.artifacts.spec = "spec.md";
  run.manifest.artifacts.design = "design.md";
  run.manifest.artifacts.plan = "plan.json";
  run.manifest.logs.scan = "logs/scan.json";
  run.manifest.scanSummary = {
    totalFiles: scan.totalFiles,
    includedFiles: scan.includedFiles.length,
    ignoredFiles: scan.ignoredFiles.count,
    readmeFiles: scan.readmeFiles.map((file) => file.path),
    docsFiles: scan.docsFiles.map((file) => file.path)
  };
  run.manifest.planSummary = {
    modules: plan.modules.length,
    language: plan.language,
    primaryExtension: plan.primaryExtension
  };
  writeManifest(paths, run);

  return {
    ok: true,
    runId: run.manifest.runId,
    status: run.manifest.status,
    artifacts: [rel(paths.root, specPath), rel(paths.root, designPath)],
    message: `已生成候选文档：${run.manifest.runId}`,
    items: [`产物：`, `  ${rel(paths.root, specPath)}`, `  ${rel(paths.root, designPath)}`],
    next: ["codespec show", "codespec apply"]
  };
}

export function generateModule(modulePath, options = {}) {
  if (!modulePath) {
    return {
      ok: false,
      code: "MISSING_MODULE_PATH",
      message: "缺少模块路径：codespec generate module <path>"
    };
  }
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const runnerError = validateRunner(options);
  if (runnerError) return runnerError;

  const latest = loadLatestRun(paths);
  const run = latest ? { dir: latest.dir, manifest: latest.manifest } : createRun(paths, "generate", options);
  const modulesDir = path.join(run.dir, "modules");
  ensureDir(modulesDir);

  const relativeModulePath = normalizeModulePath(paths.root, modulePath);
  if (!modulePathExists(paths.root, relativeModulePath)) {
    const warning = `module path not found: ${relativeModulePath}`;
    if (!run.manifest.warnings.includes(warning)) run.manifest.warnings.push(warning);
  }
  const fileName = `${slugify(relativeModulePath) || "project-root"}.md`;
  const moduleFile = path.join(modulesDir, fileName);
  fs.writeFileSync(moduleFile, moduleStub(relativeModulePath, run.manifest), "utf8");

  const artifact = `modules/${fileName}`;
  if (!run.manifest.artifacts.modules.includes(artifact)) run.manifest.artifacts.modules.push(artifact);
  run.manifest.updatedAt = new Date().toISOString();
  writeManifest(paths, run);

  return {
    ok: true,
    runId: run.manifest.runId,
    module: relativeModulePath,
    artifact: rel(paths.root, moduleFile),
    message: `已生成模块候选文档：${relativeModulePath}`,
    items: [rel(paths.root, moduleFile)],
    next: ["codespec show"]
  };
}

export function showLatestRun(options = {}) {
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const latest = loadLatestRun(paths);
  if (!latest) {
    return {
      ok: false,
      code: "NO_GENERATED_RUN",
      message: "未发现候选文档。请先执行 codespec generate。"
    };
  }
  if (options.json) return latest.manifest;

  const manifest = latest.manifest;
  const modules = manifest.artifacts.modules || [];
  const plan = readRunJson(latest, manifest.artifacts.plan);
  const scan = readRunJson(latest, manifest.logs?.scan);
  const plannedModules = plan?.modules?.length ?? manifest.planSummary?.modules ?? 0;
  const includedFiles = scan?.includedFiles?.length ?? manifest.scanSummary?.includedFiles ?? null;
  const hasFullArtifacts = Boolean(manifest.artifacts.spec && manifest.artifacts.design);
  return {
    ok: true,
    runId: manifest.runId,
    message: `候选文档：${manifest.runId}`,
    items: [
      `状态：${manifest.status}`,
      `Commit：${manifest.commitId || "unknown"}`,
      "",
      "产物：",
      manifest.artifacts.spec ? `  ${manifest.artifacts.spec}` : "  spec.md 未生成",
      manifest.artifacts.design ? `  ${manifest.artifacts.design}` : "  design.md 未生成",
      `  modules/ ${modules.length} files`,
      manifest.artifacts.plan ? `  ${manifest.artifacts.plan}` : "  plan.json 未生成",
      manifest.logs?.scan ? `  ${manifest.logs.scan}` : "  logs/scan.json 未生成",
      "",
      "摘要：",
      `  generation mode: ${manifest.generationMode || "unknown"}`,
      `  provider: ${manifest.provider || "none"}`,
      `  model: ${manifest.model || "none"}`,
      `  included files: ${includedFiles ?? "unknown"}`,
      `  planned modules: ${plannedModules}`,
      "",
      "文件位置：",
      `  ${rel(paths.root, latest.dir)}/`,
      ...(hasFullArtifacts ? [] : ["", "提示：这是 module-only run，请先执行 codespec generate 后再 apply。"])
    ],
    next: hasFullArtifacts ? ["codespec apply"] : ["codespec generate"]
  };
}

export function applyLatestRun(options = {}) {
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const latest = loadLatestRun(paths);
  if (!latest) {
    return {
      ok: false,
      code: "NO_GENERATED_RUN",
      message: "未发现候选文档。请先执行 codespec generate。"
    };
  }

  const specSource = path.join(latest.dir, "spec.md");
  const designSource = path.join(latest.dir, "design.md");
  const missing = [specSource, designSource].filter((file) => !fs.existsSync(file));
  if (missing.length) {
    return {
      ok: false,
      code: "RUN_ARTIFACT_MISSING",
      message: `候选文档不完整：${missing.map((file) => rel(paths.root, file)).join(", ")}`
    };
  }

  const specTarget = path.join(paths.specs, "spec.md");
  const designTarget = path.join(paths.specs, "design.md");
  const existing = [specTarget, designTarget].filter((file) => fs.existsSync(file));
  if (existing.length && !options.force) {
    return {
      ok: false,
      code: "APPLY_OVERWRITE_REQUIRED",
      message: "已存在 codespec/specs/spec.md 或 codespec/specs/design.md。如需覆盖，请执行 codespec apply --force。",
      existing: existing.map((file) => rel(paths.root, file))
    };
  }

  fs.mkdirSync(paths.specs, { recursive: true });
  fs.copyFileSync(specSource, specTarget);
  fs.copyFileSync(designSource, designTarget);

  latest.manifest.applied = true;
  latest.manifest.appliedAt = new Date().toISOString();
  writeManifest(paths, latest);

  return {
    ok: true,
    runId: latest.manifest.runId,
    applied: [rel(paths.root, specTarget), rel(paths.root, designTarget)],
    message: `已应用候选文档：${latest.manifest.runId}`,
    items: [rel(paths.root, specTarget), rel(paths.root, designTarget)]
  };
}

function createRun(paths, type, options = {}) {
  const runId = uniqueRunId(paths);
  const dir = path.join(paths.runtime, "runs", runId);
  fs.mkdirSync(dir, { recursive: true });
  const manifest = {
    runId,
    type,
    status: "generated",
    createdAt: new Date().toISOString(),
    root: paths.root,
    commitId: currentCommit(paths.root),
    runner: options.runner || "auto",
    generationMode: "stub",
    provider: null,
    model: options.model || null,
    probeModels: {
      requested: Boolean(options.probe_models),
      status: options.probe_models ? "not_implemented" : "not_requested"
    },
    artifacts: {
      spec: null,
      design: null,
      plan: null,
      modules: []
    },
    logs: {
      scan: null,
      llm: null,
      prompts: {}
    },
    warnings: ["P0 deterministic stub output; no LLM was called."],
    tokens: {
      input: 0,
      output: 0
    },
    applied: false
  };
  writeManifest(paths, { dir, manifest });
  return { dir, manifest };
}

function writeManifest(paths, run) {
  writeJson(path.join(run.dir, "manifest.json"), run.manifest);
  writeJson(path.join(paths.runtime, "runs", "latest.json"), {
    runId: run.manifest.runId,
    manifest: rel(paths.root, path.join(run.dir, "manifest.json"))
  });
}

function loadLatestRun(paths) {
  const latestFile = path.join(paths.runtime, "runs", "latest.json");
  const latest = readJson(latestFile);
  if (latest?.runId) {
    const dir = path.join(paths.runtime, "runs", latest.runId);
    const manifest = readJson(path.join(dir, "manifest.json"));
    if (manifest) return { dir, manifest };
  }

  const runsDir = path.join(paths.runtime, "runs");
  if (!fs.existsSync(runsDir)) return null;
  const manifests = fs
    .readdirSync(runsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const dir = path.join(runsDir, entry.name);
      return { dir, manifest: readJson(path.join(dir, "manifest.json")) };
    })
    .filter((run) => run.manifest?.createdAt)
    .sort((a, b) => String(b.manifest.createdAt).localeCompare(String(a.manifest.createdAt)));
  return manifests[0] || null;
}

function projectInitializationError(paths) {
  if (!fs.existsSync(paths.runtime) || !fs.existsSync(paths.codespec)) {
    return {
      ok: false,
      code: "CODESPEC_NOT_INITIALIZED",
      message: "缺少 CodeSpec 项目结构。请先执行 codespec init。",
      next: ["codespec init"]
    };
  }
  return null;
}

function validateRunner(options) {
  const runner = options.runner || "auto";
  if (runner === "auto") return null;
  return {
    ok: false,
    code: "RUNNER_NOT_IMPLEMENTED",
    runner,
    message: `P0 暂未实现 --runner ${runner}。请使用默认 runner 或 --runner auto。`,
    next: ["codespec generate"]
  };
}

function uniqueRunId(paths) {
  const base = timestampId();
  let runId = base;
  let suffix = 1;
  while (fs.existsSync(path.join(paths.runtime, "runs", runId))) {
    suffix += 1;
    runId = `${base}-${suffix}`;
  }
  return runId;
}

function timestampId(date = new Date()) {
  const pad = (value, size = 2) => String(value).padStart(size, "0");
  return [
    date.getFullYear(),
    pad(date.getMonth() + 1),
    pad(date.getDate()),
    pad(date.getHours()),
    pad(date.getMinutes()),
    pad(date.getSeconds()),
    pad(date.getMilliseconds(), 3)
  ].join("");
}

function currentCommit(root) {
  const result = spawnSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
    timeout: 2000
  });
  return result.status === 0 ? result.stdout.trim() : null;
}

function normalizeModulePath(root, modulePath) {
  const resolved = path.isAbsolute(modulePath) ? modulePath : path.join(root, modulePath);
  const relative = normalizePath(path.relative(root, resolved));
  return relative && !relative.startsWith("..") ? relative : normalizePath(modulePath);
}

function modulePathExists(root, modulePath) {
  if (modulePath === ".") return true;
  return fs.existsSync(path.join(root, modulePath));
}

function readRunJson(run, relativePath) {
  if (!relativePath) return null;
  return readJson(path.join(run.dir, relativePath), null);
}

function designStub(root, manifest) {
  return `${STUB_MARKER}
# CodeSpec Design

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. 组件定位

这是 P0 deterministic stub 设计文档，用于验证 CodeSpec CLI 的候选文档生成链路。

## 2. 架构总览

P0 不连接真实 LLM，也不调用外部 agent。CLI 只负责创建 run 目录、写入产物和维护 manifest。

## 3. 模块设计

模块文档会保存在当前 run 的 modules/ 目录中，不会进入权威规格目录。

## 4. 核心流程

generate 写入候选文档，show 展示最近 run，apply 在覆盖保护下写入 codespec/specs。

## 5. 接口设计

用户入口为 codespec generate、codespec show、codespec apply 和 codespec generate module <path>。

## 6. 数据模型

manifest.json 记录 runId、状态、产物、runner、模型探测设计和 apply 状态。

## 7. 配置与部署

init 会记录本地 coding agent 的 PATH 探测结果，但 P0 不默认调用远端模型。

## 8. DFX 设计

默认不覆盖已有权威文档，必须显式传入 --force。

## 9. 风险与约束

stub 内容仅用于 P0 验收，不能代表真实项目设计结论。
`;
}

function specStub(root, manifest) {
  return `${STUB_MARKER}
# CodeSpec SPEC

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. 组件定位

该组件通过 CodeSpec CLI 管理候选文档与权威文档的发布流程。

## 2. 领域术语

- 候选文档：生成后保存在 run 目录、尚未应用的文档。
- 权威文档：位于 codespec/specs 的 spec.md 与 design.md。
- run：一次生成动作产生的隔离结果目录。

## 3. 角色与边界

CLI 负责落盘、展示和应用文档。P0 不让任何外部 agent 写入权威文档。

## 4. DFX 约束

应用候选文档时必须遵守覆盖保护；已有权威文档默认不被覆盖。

## 5. 功能规格

- 用户可以生成候选 spec.md 与 design.md。
- 用户可以查看最近一次候选文档摘要。
- 用户可以显式应用最近一次候选文档。
- 用户可以为单个模块生成 stub 审查材料。

## 6. 验收标准

- generate 只写入 .codespec-cli/runs。
- show 可以返回最近 run 的 manifest。
- apply 在无 --force 且目标存在时失败。
- sync --generate 与 generate 使用相同本地生成流程。
`;
}

function moduleStub(modulePath, manifest) {
  return `${STUB_MARKER}
# Module Design: ${modulePath}

Run: ${manifest.runId}

## 1. 模块定位

这是针对 ${modulePath} 的 P0 deterministic stub 模块文档。

## 2. 目录结构

P0 不扫描真实文件树；后续阶段会补充仓库扫描和模块规划。

## 3. 核心组件

待真实生成阶段根据代码分析补充。

## 4. 核心流程

该文件只保存在 run 的 modules/ 目录中，不会由 apply 写入 codespec/specs。

## 5. 接口与数据结构

待确认。

## 6. 关键约束

P0 不调用 LLM 或外部 runner。
`;
}
